Updated to most recent version/changes from mainline.

diff --git a/ports/opt-ppc/rust/Pkgfile b/ports/opt-ppc/rust/Pkgfile
--- a/ports/opt-ppc/rust/Pkgfile
+++ b/ports/opt-ppc/rust/Pkgfile
@@ -1,37 +1,42 @@
 # Description: The Rust language with Cargo included.
-# URL: http://www.rust-lang.org/
+# URL: https://www.rust-lang.org/
 # Maintainer: cruxppc at gmail dot com
 # Depends on: llvm
-# Optional: sccache llvm-32
+# Optional: sccache
 
 name=rust
-version=1.40.0
-##cat src/stage0.txt
-_date=2019-11-07
-_rustc=1.39.0
-_cargo=0.40.0
-##
-
+version=1.48.0
+_date=2020-10-08
+_rustc=1.47.0
+_cargo=0.48.0
+_llvm=10.0.1
 release=1
 source=(
-	https://static.rust-lang.org/dist/${name}c-$version-src.tar.gz
-	https://static.rust-lang.org/dist/$_date/rust-std-$_rustc-powerpc-unknown-linux-gnu.tar.gz
-	https://static.rust-lang.org/dist/$_date/rustc-$_rustc-powerpc-unknown-linux-gnu.tar.gz
-	https://static.rust-lang.org/dist/$_date/cargo-$_cargo-powerpc-unknown-linux-gnu.tar.gz
-	ppcfixes.patch
-	0007-Fix-C-aggregate-passing-ABI-on-powerpc.patch
-	0008-Fix-zero-sized-aggregate-ABI-on-powerpc.patch
-	0010-test-c-variadic-Fix-patterns-on-powerpc64.patch
-	0040-rls-atomics.patch
+	https://static.rust-lang.org/dist/${name}c-$version-src.tar.xz
+	https://static.rust-lang.org/dist/$_date/rust-std-$_rustc-powerpc-unknown-linux-gnu.tar.xz
+	https://static.rust-lang.org/dist/$_date/rustc-$_rustc-powerpc-unknown-linux-gnu.tar.xz
+	https://static.rust-lang.org/dist/$_date/cargo-$_cargo-powerpc-unknown-linux-gnu.tar.xz
+	https://github.com/llvm/llvm-project/releases/download/llvmorg-$_llvm/compiler-rt-$_llvm.src.tar.xz
 )
- 
+
+unpack_source() {
+	for file in ${source[@]}; do
+		case ${file##*/} in
+			rustc-${version}-src.tar.xz|compiler-rt-${_llvm}.src.tar.xz)
+			echo "Unpacking $(get_filename $file)";
+			bsdtar -p -o -C ${SRC} -xf $(get_filename $file) ;;
+		*.tar.xz)
+			echo "Copying $(get_filename $file)";
+			mkdir -p ${SRC}/${name}c-$version-src/build/cache/${_date} || true
+			cp $(get_filename $file) ${SRC}/${name}c-$version-src/build/cache/${_date} ;;
+		*)
+			cp $(get_filename $file) ${SRC} ;;
+		esac
+	done
+}
+
 build() {
 	cd "${name}c-$version-src"
-	patch -p1 -i $SRC/0040-rls-atomics.patch
-	#patch -p1 -i $SRC/ppcfixes.patch
-	#patch -p1 -i $SRC/0007-Fix-C-aggregate-passing-ABI-on-powerpc.patch
-	#patch -p1 -i $SRC/0008-Fix-zero-sized-aggregate-ABI-on-powerpc.patch
-	#patch -p1 -i $SRC/0010-test-c-variadic-Fix-patterns-on-powerpc64.patch
 
 	local ERROR
 	local DATE="$(awk '/^date: / { print $2 }' src/stage0.txt)"
@@ -52,18 +57,9 @@ build() {
 	[ $ERROR ] && exit 1
 	unset DATE RUSTC CARGO ERROR
 
-	mkdir -p build/cache/$_date
-	cp $PKGMK_SOURCE_DIR/rust-std-$_rustc-powerpc-unknown-linux-gnu.tar.gz build/cache/$_date/
-	cp $PKGMK_SOURCE_DIR/rustc-$_rustc-powerpc-unknown-linux-gnu.tar.gz build/cache/$_date/
-	cp $PKGMK_SOURCE_DIR/cargo-$_cargo-powerpc-unknown-linux-gnu.tar.gz build/cache/$_date/
-
-	prt-get isinst sccache && export RUSTC_WRAPPER=/usr/bin/sccache
-
 cat <<- EOF > $SRC/config.toml
 	[llvm]
 	ninja = true
-	targets = "ppc"
-	experimental-targets = ""
 	link-shared = true
 
 	[install]
@@ -72,53 +68,71 @@ cat <<- EOF > $SRC/config.toml
 	[rust]
 	channel = "stable"
 	rpath = false
-	codegen-tests = false
-	backtrace-on-ice = true
+	codegen-units-std = 1
+	debuginfo-level-std = 2
 
 	[build]
+	target = ["powerpc-unknown-linux-gnu"]
+	tools = ["cargo", "rls", "clippy", "miri", "rustfmt", "analysis", "src"]
 	docs = false
 	extended = true
-	python = "python3"
-EOF
-	# part of [build] options
-        if [ -e '/usr/bin/rustc' ]; then
-		if [ -z "$(/usr/bin/ldd /usr/lib/rustlib/powerpc-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so | egrep '.*libLLVM-.*.so => not found')" ]; then
-cat <<- EOF >> $SRC/config.toml
-	cargo = "/usr/bin/cargo"
-	rustc = "/usr/bin/rustc"
-EOF
-		else
-			printf "\e[031mllvm broken symlink detected, not using system rust to bootstrap\033[0m\n"
-		fi
-        fi
+	sanitizers = false
+	profiler = true
+	vendor = true
+	python = "/usr/bin/python3"
+	@CARGO@
+	@RUST@
 
-cat <<- EOF >> $SRC/config.toml
 	[target.powerpc-unknown-linux-gnu]
 	llvm-config = "/usr/bin/llvm-config"
 EOF
 
-#	if [ -e '/usr/bin/llvm-config-32' ]; then
-#cat <<- EOF >> $SRC/config.toml
-#	[target.i686-unknown-linux-gnu]
-#	llvm-config = "/usr/bin/llvm-config-32"
-#EOF
-#	fi
+	if [ -e '/usr/bin/rustc' ]; then
+		if [ -z "$(/usr/bin/ldd /usr/bin/rustc | egrep '.*libLLVM.*.so => not found')" ]; then
+			sed	-e 's|@CARGO@|cargo = "/usr/bin/cargo"|' \
+				-e 's|@RUST@|rustc = "/usr/bin/rustc"|' \
+				-i $SRC/config.toml
+		else
+			sed -e 's|@CARGO@||' -e 's|@RUST@||' -i $SRC/config.toml
+			printf "\e[031mllvm broken symlink detected, not using system rust to bootstrap\033[0m\n"
+		fi
+	else
+		sed -e 's|@CARGO@||' -e 's|@RUST@||' -i $SRC/config.toml
+	fi
 
 	cat $SRC/config.toml
 
 	mkdir "$PKGMK_SOURCE_DIR/rust" || true
 	export CARGO_HOME="$PKGMK_SOURCE_DIR/rust"
 
-	export RUSTFLAGS="$RUSTFLAGS -C link-args=-lffi"
-	/usr/bin/python3 ./x.py build --config="${SRC}"/config.toml --exclude src/tools/miri -j ${JOBS-1}
+        if [ -e '/usr/bin/sccache' ]; then
+                export RUSTC_WRAPPER='/usr/bin/sccache'
+                export SCCACHE_IDLE_TIMEOUT='1500'
+        fi
 
-	export LIBSSH2_SYS_USE_PKG_CONFIG=1
+	export RUST_BACKTRACE=1
+	export RUST_COMPILER_RT_ROOT="$SRC/compiler-rt-$_llvm.src"
+	/usr/bin/python3 ./x.py build --config="${SRC}"/config.toml -j $(nproc)
 	DESTDIR=$PKG /usr/bin/python3 ./x.py --config="${SRC}"/config.toml install
-	unset LIBSSH2_SYS_USE_PKG_CONFIG
 
-	#cleanup
+	[ -e '/usr/bin/zsh' ] || rm -r $PKG/usr/share/zsh
+
+	# cleanup
 	rm -r $PKG/usr/share/doc
-	rm -r $PKG/usr/share/zsh
 	rm -r $PKG/etc
 	rm $PKG/usr/lib/rustlib/{components,manifest-rustc,rust-installer-version,uninstall.sh}
+
+	# Remove analysis data for libs that weren't installed
+	local file lib
+	while read -rd '' file; do
+		lib="${file%.json}.rlib"
+		lib="${lib/\/analysis\///lib/}"
+		if [[ ! -e $lib ]]; then
+			echo "missing '$lib'"
+			rm -v "$file"
+		fi
+	done < <(find "$PKG/usr/lib/rustlib"  -path '*/analysis/*.json' -print0)
+
+	install -d $PKG/etc/revdep.d
+	#echo "/usr/lib/rustlib/i686-unknown-linux-gnu/lib" > $PKG/etc/revdep.d/rust
 }
