Replaced mainline scripts with ppc versions adapted from 2.7 iso. Should be looked at further.

diff --git a/iso/iso/bin/setup b/iso/iso/bin/setup
--- a/iso/iso/bin/setup
+++ b/iso/iso/bin/setup
@@ -1,8 +1,12 @@
 #!/bin/bash
 #
-# CRUX Setup
+# CRUX PPC Setup, based on CRUX Setup
 #
-# Copyright (c) 2001-2005 by Per Liden <per@fukt.bth.se>
+# Copyright (c) 2001-2004 by Per Liden <per@fukt.bth.se> 
+# Copyright (c) 2004 Giulivo Navigante <giulivo@linuxmail.org>
+# Copyright (c) 2005-2011 The CRUX PPC Team - http://cruxppc.org/
+#
+# release codename is: ottobre 2010
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -18,16 +22,15 @@
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, 
 # USA.
-#
 
-VERSION="3.5"
+VERSION="3.5 "
 
 do_dialog() {
-    dialog --backtitle "CRUX $VERSION Setup" --no-shadow "$@"
+    dialog --backtitle "Setup: CRUX PPC $VERSION (32bit) " --no-shadow "$@"
 }
 
 do_abort() {
-    do_dialog --aspect 50 --defaultno --yesno "Abort installation?" 0 0 && exit 1
+    do_dialog --aspect 50 --defaultno --yesno "WARNING: Abort installation?" 0 0 && exit 1
 }
 
 do_select() {
@@ -42,31 +45,31 @@ do_select() {
 }
 
 welcome() {
-    do_select --aspect 5 --yesno "Welcome!\n\nThis script will guide you through the installation of CRUX packages.\n\nBefore starting the installation make sure you have read and understood the \"CRUX Installation Guide\". If you have done that then please continue, else abort the installation and come back later.\n\nAre you really sure you want to continue?" 0 0
+    do_select --aspect 5 --yesno "Welcome!\n\nThis script will guide you through the installation of CRUX PPC packages.\n\nBefore starting the installation make sure you have read and understood the \"CRUX PPC Installation Guide\". If you have done that then please continue, else abort the installation and come back later.\n\nAre you really sure you want to continue?" 0 0
 }
 
 select_action() {
     do_select --menu "Install or upgrade?" 9 45 2 \
-	             "1" "Install CRUX $VERSION" \
-                     "2" "Upgrade to CRUX $VERSION" 2> $tmpfile
+	"1" "Install CRUX PPC $VERSION " \
+	"2" "Upgrade to CRUX PPC $VERSION " 2> $tmpfile
     ACTION=`cat $tmpfile`
     if [ "$ACTION" = "1" ]; then
 	ACTION="INSTALL"
     else
 	ACTION="UPGRADE"
-	do_select --aspect 5 --yesno "NOTE!\n\nBefore upgrading make sure /etc/pkgadd.conf in the old installation is tuned to fit your needs, important files might otherwise be overwritten. Further, when setup has completed the upgrade you need to go though the rejected files in /var/lib/pkg/rejected/ and upgrade them manually if needed (or use the rejmerge(8) tool). See the pkgadd(8) man page for more information about /etc/pkgadd.conf.\n\nAre you really sure you want to continue?" 0 0
+	do_select --aspect 5 --yesno "NOTE!\n\nBefore upgrading make sure /etc/pkgadd.conf in the old installation is tuned to fit your needs, important files might otherwise be overwritten. Further, when this script has completed the upgrade you need to go though the rejected files in /var/lib/pkg/rejected/ and upgrade them manually if needed. See the pkgadd(8) man page for more information about /etc/pkgadd.conf.\n\nAre you really sure you want to continue?" 0 0
     fi
 }
 
 select_root() {
     while true; do
-	do_select --aspect 40 --inputbox "Enter directory where your CRUX root partition is mounted:" 0 0 "/mnt" 2> $tmpfile
+	do_select --aspect 40 --inputbox "Enter directory where your CRUX PPC root partition is mounted:" 0 0 "/mnt" 2> $tmpfile
 	ROOT=`cat $tmpfile`
 	if [ -d "$ROOT" ]; then
 	    if [ "$ACTION" = "INSTALL" ] || [ -f "$ROOT/var/lib/pkg/db" ]; then
 		break
 	    fi
-	    do_dialog --aspect 50 --msgbox "Directory does not look like a CRUX root directory. Try again." 0 0
+	    do_dialog --aspect 50 --msgbox "Directory does not look like a CRUX PPC root directory. Try again." 0 0
 	else
 	    do_dialog --aspect 50 --msgbox "Directory not found. Try again." 0 0
 	fi
@@ -74,132 +77,110 @@ select_root() {
 }
 
 select_collections() {
-	if [ "$ACTION" != "INSTALL" ]; then
-		return 0
-	fi
-	if [ ! -d core ] || [ ! -d opt ] || [ ! -d xorg ] || [ ! -d kernel ]; then
-		do_dialog --aspect 50 --msgbox "Package directories (core, opt, xorg or kernel) were not found in $crux_dir. Aborting." 0 0
-		exit 1
-	fi
-	TITLE="Select collections to install:\n(detailed package selection will follow)"
-	do_select --separate-output --checklist "$TITLE" 13 60 6 \
-		core "The core packages (required)" ON \
-		opt "Optional packages" OFF \
-		xorg "X.org packages" OFF 2> $collfile
+    if [ "$ACTION" != "INSTALL" ]; then
+	return 0
+    fi
+    if [ ! -d core ] || [ ! -d opt ] || [ ! -d xorg ] || [ ! -d kernel ]; then
+	do_dialog --aspect 50 --msgbox "Package directories (core, opt, xorg or kernel) were not found in $crux_dir. Aborting." 0 0
+	exit 1
+    fi
+    TITLE="Select collections to install:\n(detailed package selection will follow)"
+    do_select --separate-output --checklist "$TITLE" 13 60 6 \
+	core "The core packages (required)" ON \
+	opt "Optional packages" OFF \
+	xorg "X.org packages" OFF 2> $collfile
+    sed -i 's|\"||g' $collfile
 }
 
 ask_detailed() {
-	if [ "$ACTION" != "INSTALL" ]; then
-		return 0
-	fi
-	do_dialog --aspect 50 --defaultno --yesno "Do you want the chance to select packages individually?" 0 0 && DO_DETAILED="yes"
+    if [ "$ACTION" != "INSTALL" ]; then
+	return 0
+    fi
+    do_dialog --aspect 50 --defaultno --yesno "Do you want the chance to select packages individually?" 0 0 && DO_DETAILED="yes"
 }
 
 select_packages() {
-	if [ ! -d core ] || [ ! -d opt ] || [ ! -d xorg ] || [ ! -d kernel ]; then
-		do_dialog --aspect 50 --msgbox "Package directories (core, opt, xorg, and kernel) were not found in $crux_dir. Aborting." 0 0
-		exit 1
-	fi
-	if [ "$ACTION" = "INSTALL" ]; then
-		if [ "$DO_DETAILED" = "yes" ]; then
-			for collection in core opt xorg; do
-				presel=`grep $collection $collfile`
-				if [ "$presel" == "$collection" ]; then
-					checked=ON
-				else
-					checked=OFF
-				fi
-				do_dialog --aspect 50 --infobox "Searching for packages, please wait..." 0 0
-				TITLE="Select $collection packages to install:"
-				find $collection \( -name '*.pkg.tar.gz' -o -name '*.pkg.tar.bz2' -o -name '*.pkg.tar.xz' \) -printf "%f ($collection) $checked\n" | sed 's/.pkg.tar.[^ ]*//g' | sort > $tmpfile
-				# prune bootloaders from the list for later selection
-				for bootloader in ${bootloaders[@]}; do
-					sed -i -e "/$bootloader/d" $tmpfile
-				done
-				PKG_LIST=`cat $tmpfile | xargs echo ' '`
-				do_select --separate-output --checklist "$TITLE" 19 60 12 $PKG_LIST 2>> $pkgfile
-			done
-		else # no detailed selection
-			for collection in core opt xorg; do
-				presel=`grep $collection $collfile`
-				if [ "$presel" == "$collection" ]; then
-					find $collection \( -name '*.pkg.tar.gz' -o -name '*.pkg.tar.bz2' -o -name '*.pkg.tar.xz' \) -printf "%f\n" | sed 's/.pkg.tar.*//g' | sort >> $pkgfile
-				fi
-			done
-			# prune bootloaders from the list for later selection
-			for bootloader in ${bootloaders[@]}; do
-				sed -i -e "/$bootloader/d" $pkgfile
-			done
+    if [ ! -d core ] || [ ! -d opt ] || [ ! -d xorg ] || [ ! -d kernel ]; then
+	do_dialog --aspect 50 --msgbox "Package directories (core, opt, xorg or kernel) were not found in $crux_dir. Aborting." 0 0
+	exit 1
+    fi
+    if [ "$ACTION" = "INSTALL" ]; then
+	if [ "$DO_DETAILED" = "yes" ]; then
+	    for collection in core opt xorg; do
+		presel=`grep $collection $collfile`
+		if [ "$presel" == "$collection" ]; then
+		    checked=ON
+		else
+		    checked=OFF
 		fi
-	else
-		# Upgrade
 		do_dialog --aspect 50 --infobox "Searching for packages, please wait..." 0 0
-		TITLE="Select packages to upgrade:"
-		INSTALLED_PACKAGES=`pkginfo -r $ROOT -i | gawk '{ print $1; }'`
-		for package in $INSTALLED_PACKAGES; do
-			CORE_LIST="$CORE_LIST `find core \( -name \"${package}#*.pkg.tar.gz\" -o -name \"${package}#*.pkg.tar.bz2\" -o -name \"${package}#*.pkg.tar.xz\" \) -printf '%f (core) ON\n' | sed 's/.pkg.tar.[^ ]*/ /g' | sort | xargs echo ' '`"
-			OPT_LIST="$OPT_LIST `find opt \( -name \"${package}#*.pkg.tar.gz\" -o -name \"${package}#*.pkg.tar.bz2\" -o -name \"${package}#*.pkg.tar.xz\" \) -printf '%f (opt) ON\n' | sed 's/.pkg.tar.[^ ]*/ /g' | sort | xargs echo ' '`"
-			XORG_LIST="$XORG_LIST `find xorg \( -name \"${package}#*.pkg.tar.gz\" -o -name \"${package}#*.pkg.tar.bz2\" -o -name \"${package}#*.pkg.tar.xz\" \) -printf '%f (xorg) ON\n' | sed 's/.pkg.tar.[^ ]*/ /g' | sort | xargs echo ' '`"
-		done
-		do_select --separate-output --checklist "$TITLE" 19 60 12 $CORE_LIST $OPT_LIST $XORG_LIST 2> $pkgfile
+		TITLE="Select $collection packages to install:"
+		PKG_LIST=`find $collection \( -name '*.pkg.tar.gz' -o -name '*.pkg.tar.bz2' -o -name '*.pkg.tar.xz' \) -printf "%f ($collection) $checked\n" | sed 's/.pkg.tar.[^ ]*//g' | sort | xargs echo ' '`
+		do_select --separate-output --checklist "$TITLE" 19 60 12 $PKG_LIST 2>> $pkgfile
+	    done
+	else # no detailed selection
+	    for collection in core opt xorg; do
+		presel=`grep $collection $collfile`
+		if [ "$presel" == "$collection" ]; then
+		    find $collection \( -name '*.pkg.tar.gz' -o -name '*.pkg.tar.bz2' -o -name '*.pkg.tar.xz' \) -printf "%f\n" | sed 's/.pkg.tar.*//g' | sort >> $pkgfile
+		fi
+	    done
 	fi
-}
-
-select_bootloader() {
-	if [ ! -d core ] || [ ! -d opt ] || [ ! -d xorg ] || [ ! -d kernel ]; then
-		do_dialog --aspect 50 --msgbox "Package directories (core, opt, xorg, and kernel) were not found in $crux_dir. Aborting." 0 0
-		exit 1
-	fi
-
-	if [ "$ACTION" = "INSTALL" ]; then
-		for package in ${bootloaders[@]}; do
-			# currently bootloaders only exist in opt but just in case that changes in the future...
-			BOOTLOADER_LIST="$BOOTLOADER_LIST `find core \( -name \"${package}#*.pkg.tar.gz\" -o -name \"${package}#*.pkg.tar.xz\" -o -name \"${package}#*.pkg.tar.bz2\" \) -printf '%f (core) OFF\n' | sed 's/.pkg.tar.[^ ]*/ /g' | sort | xargs echo ' '`"
-			BOOTLOADER_LIST="$BOOTLOADER_LIST `find opt \( -name \"${package}#*.pkg.tar.gz\" -o -name \"${package}#*.pkg.tar.xz\" -o -name \"${package}#*.pkg.tar.bz2\" \) -printf '%f (opt) OFF\n' | sed 's/.pkg.tar.[^ ]*/ /g' | sort | xargs echo ' '`"
-			BOOTLOADER_LIST="$BOOTLOADER_LIST `find xorg \( -name \"${package}#*.pkg.tar.gz\" -o -name \"${package}#*.pkg.tar.xz\" -o -name \"${package}#*.pkg.tar.bz2\" \) -printf '%f (xorg) OFF\n' | sed 's/.pkg.tar.[^ ]*/ /g' | sort | xargs echo ' '`"
-		done
-		TITLE="Select bootloader:\n(at least one should be selected)"
-		do_select --separate-output --checklist "$TITLE" 19 60 12 $BOOTLOADER_LIST 2>> $pkgfile
-	fi
+    else
+        # Upgrade
+	do_dialog --aspect 50 --infobox "Searching for packages, please wait..." 0 0
+	TITLE="Select packages to upgrade:"
+	INSTALLED_PACKAGES=`pkginfo -r $ROOT -i | gawk '{ print $1; }'`
+	for package in $INSTALLED_PACKAGES; do
+	    CORE_LIST="$CORE_LIST `find core \( -name \"${package}#*.pkg.tar.gz\" -o -name \"${package}#*.pkg.tar.bz2\" -o -name \"${package}#*.pkg.tar.xz\" \) -printf '%f (core) ON\n' | sed 's/.pkg.tar.[^ ]*/ /g' | sort | xargs echo ' '`"
+	    OPT_LIST="$OPT_LIST `find opt \( -name \"${package}#*.pkg.tar.gz\" -o -name \"${package}#*.pkg.tar.bz2\" -o -name \"${package}#*.pkg.tar.xz\" \) -printf '%f (opt) ON\n' | sed 's/.pkg.tar.[^ ]*/ /g' | sort | xargs echo ' '`"
+	    XORG_LIST="$XORG_LIST `find xorg \( -name \"${package}#*.pkg.tar.gz\" -o -name \"${package}#*.pkg.tar.bz2\" -o -name \"${package}#*.pkg.tar.xz\" \) -printf '%f (xorg) ON\n' | sed 's/.pkg.tar.[^ ]*/ /g' | sort | xargs echo ' '`"
+	done
+	do_select --separate-output --checklist "$TITLE" 19 60 12 $CORE_LIST $OPT_LIST $XORG_LIST 2> $pkgfile
+    fi
+    sed -i 's|\"||g' $pkgfile
+    sed -i 's|\\\#|\#|g' $pkgfile
 }
 
 check_dependencies() {
-	if [ "$ACTION" != "INSTALL" ]; then
-		return 0
-	fi
-	do_dialog --aspect 50 --infobox "Checking dependencies, please wait..." 0 0
-	get_missing_deps
-	if [ -n "$MISSING_DEPS" ]; then
-		for package in $MISSING_DEPS; do
-		    MISSING_LIST="$MISSING_LIST `find . \( -name \"${package}#*.pkg.tar.gz\" -o -name \"${package}#*.pkg.tar.bz2\" -o -name \"${package}#*.pkg.tar.xz\" \) -printf '%f %p ON\n' | sed 's/.pkg.tar.[^ ]*/ /g' | sed 's|./|(|;s|/.* O|) O|' | sort | xargs echo ' '`"
-		done
-		TITLE="The following packages are needed by the ones you selected"
-		do_select --separate-output --checklist "$TITLE" 19 60 12 $MISSING_LIST 2>> $pkgfile
-	fi
+    if [ "$ACTION" != "INSTALL" ]; then
+	return 0
+    fi
+    do_dialog --aspect 50 --infobox "Checking dependencies, please wait..." 0 0
+    get_missing_deps
+    if [ -n "$MISSING_DEPS" ]; then
+	for package in $MISSING_DEPS; do
+	    MISSING_LIST="$MISSING_LIST `find . \( -name \"${package}#*.pkg.tar.gz\" -o -name \"${package}#*.pkg.tar.bz2\" -o -name \"${package}#*.pkg.tar.xz\" \) -printf '%f %p ON\n' | sed 's/.pkg.tar.[^ ]*/ /g' | sed 's|./|(|;s|/.* O|) O|' | sort | xargs echo ' '`"
+	done
+	TITLE="The following packages are needed by the ones you selected"
+	do_select --separate-output --checklist "$TITLE" 19 60 12 $MISSING_LIST 2>> $pkgfile
+    fi
+    sed -i 's|\"||g' $pkgfile
+    sed -i 's|\\\#|\#|g' $pkgfile
 }
 
 get_missing_deps() {
-	needed=""
-	toinstall=`sed 's/\#.*//g' $pkgfile`
-	for f in $toinstall; do
-		pdeps=`grep "^$f\:" $depsfile|sed "s|^$f: ||g"`
-		for d in $pdeps; do
-			needed="$needed $d"
-		done
+    needed=""
+    toinstall=`sed 's/\#.*//g' $pkgfile`
+    for f in $toinstall; do
+	pdeps=`grep "^$f\:" $depsfile|sed "s|^$f: ||g"`
+	for d in $pdeps; do
+	    needed="$needed $d"
 	done
-	sed 's/\#.*//g' $pkgfile|sort -u > $markedfile
-	echo $needed|tr ' ' '\n'|sort -u > $neededfile
-	MISSING_DEPS=`comm -1 -3 $markedfile $neededfile`
+    done
+    sed 's/\#.*//g' $pkgfile|sort -u > $markedfile
+    echo $needed|tr ' ' '\n'|sort -u > $neededfile
+    MISSING_DEPS=`comm -1 -3 $markedfile $neededfile`
 }
 
 confirm() {
-	if [ "$ACTION" = "INSTALL" ]; then
-		# Install
-		do_select --aspect 25 --yesno "Selected packages will now be installed. Are you sure you want to continue?" 0 0
-	else
-		# Upgrade
-		do_select --aspect 25 --yesno "Selected packages will now be upgraded. Are you sure you want to continue?" 0 0
-	fi
+    if [ "$ACTION" = "INSTALL" ]; then
+	# Install
+	do_select --aspect 25 --yesno "Selected packages will now be installed. Are you sure you want to continue?" 0 0
+    else
+	# Upgrade
+	do_select --aspect 25 --yesno "Selected packages will now be upgraded. Are you sure you want to continue?" 0 0
+    fi
 }
 
 progressbar() {
@@ -262,40 +243,45 @@ install_packages() {
 	done
 
 	# Install kernel
-	if [ ! -d $ROOT/usr/src/linux-$KERNEL_VERSION ]; then
-	    progressbar "Installing `basename $KERNEL .tar.xz`..."
-	    echo -n "Installing `basename $KERNEL .tar.xz`....." >> $logfile
-	    (
-		set -e
-		tar -C $ROOT/usr/src -xJf $KERNEL
-		cp -f ./kernel/linux-$KERNEL_VERSION.defconfig $ROOT/usr/src/linux-$KERNEL_VERSION/.config
-		chown -R root.root $ROOT/usr/src/linux-$KERNEL_VERSION
-		chmod -R go-w $ROOT/usr/src/linux-$KERNEL_VERSION
-		shopt -s nullglob
-		# modified to be filename-agnostic
-		#for patch in ./kernel/linux-$KERNEL_VERSION-*.patch; do
-		for patch in ./kernel/*patch; do
-		    patch -s -d $ROOT/usr/src/linux-$KERNEL_VERSION -p1 < $patch
-			cp $patch $ROOT/usr/src/
-		done
-		if [ ! -d $ROOT/lib/modules/$KERNEL_VERSION ]; then
-		    mkdir -p $ROOT/lib/modules/$KERNEL_VERSION
-		    depmod -b $ROOT -a $KERNEL_VERSION
-		fi
-	    ) > $tmpfile 2>&1
-	    if [ $? = 0 ]; then
-		echo "OK" >> $logfile
-	    else
-		let $((ERRORS+=1))
-		echo "ERROR" >> $logfile
-		echo "" >> $logfile
-		cat $tmpfile >> $logfile
-		echo "" >> $logfile
-	    fi
-	else
-	    echo "Directory $ROOT/usr/src/linux-$KERNEL_VERSION already exists." >> $logfile
-	    echo "Assuming linux-$KERNEL_VERSION is already installed." >> $logfile
-	fi
+# SKIP kernel install for now
+#	if [ ! -d $ROOT/usr/src/linux-$KERNEL_VERSION ]; then
+#	    progressbar "Installing `basename $KERNEL .tar.xz`..."
+#	    echo -n "Installing `basename $KERNEL .tar.xz`....." >> $logfile
+#	    (
+#		set -e
+#		tar -C $ROOT/usr/src -xjf $KERNEL
+##		cp -f ./kernel/linux-$KERNEL_VERSION.config $ROOT/usr/src/linux-$KERNEL_VERSION/.config
+##		cp -f ./kernel/linux-$KERNEL_VERSION.patch $ROOT/usr/src/
+#		cp -f ./kernel/cruxppc-logo.diff $ROOT/usr/src/
+#		for config in ./kernel/*config; do
+#		    cp $config $ROOT/usr/src/
+#		done
+#		
+#		chown -R root.root $ROOT/usr/src/linux-$KERNEL_VERSION
+#		chmod -R go-w $ROOT/usr/src/linux-$KERNEL_VERSION
+#		shopt -s nullglob
+#		for patch in ./kernel/*patch; do
+##		    patch -s -d $ROOT/usr/src/linux-$KERNEL_VERSION -p1 < $patch
+#		    cp $patch $ROOT/usr/src/
+#		done
+#		if [ ! -d $ROOT/lib/modules/$KERNEL_VERSION ]; then
+#		    mkdir -p $ROOT/lib/modules/$KERNEL_VERSION
+#		    depmod -b $ROOT -a $KERNEL_VERSION
+#		fi
+#	    ) > $tmpfile 2>&1
+#	    if [ $? = 0 ]; then
+#		echo "OK" >> $logfile
+#	    else
+#		let $((ERRORS+=1))
+#		echo "ERROR" >> $logfile
+#		echo "" >> $logfile
+#		cat $tmpfile >> $logfile
+#		echo "" >> $logfile
+#	    fi
+#	else
+#	    echo "Directory $ROOT/usr/src/linux-$KERNEL_VERSION already exists." >> $logfile
+#	    echo "Assuming linux-$KERNEL_VERSION is already installed." >> $logfile
+#	fi
 
         # Log footer
 	echo "----------------------------------------------------------" >> $logfile
@@ -320,33 +306,21 @@ install_packages() {
 }
 
 main() {
-	welcome
-	select_action
-	select_root
-	select_collections
-	ask_detailed
-	select_packages
-	select_bootloader
-	check_dependencies
-	confirm
-	if [ "$ACTION" = "UPGRADE" ] && [ -f /usr/bin/setup-helper ]
-	then
-		(/usr/bin/setup-helper $ROOT &> $helperlogfile) | do_dialog \
-			--title " Please wait [3.4 -> 3.5 check]" --gauge "" 8 60 0
-	fi
-	install_packages
-
-	# one-time fix for .inactive ports files
-	if [ -f $ROOT/etc/ports/contrib.rsync.inactive -a -f $ROOT/etc/ports/contrib.rsync ]; then
-		mkdir -p $ROOT/var/lib/pkg/rejected/etc/ports
-		mv -f $ROOT/etc/ports/contrib.rsync.inactive $ROOT/var/lib/pkg/rejected/etc/ports/contrib.rsync
-	fi
-	if [ -f $ROOT/etc/ports/compat-32.rsync.inactive -a -f $ROOT/etc/ports/compat-32.rsync ]; then
-		mkdir -p $ROOT/var/lib/pkg/rejected/etc/ports
-		mv -f $ROOT/etc/ports/compat-32.rsync.inactive $ROOT/var/lib/pkg/rejected/etc/ports/compat-32.rsync
-	fi
-
-	cat $helperlogfile 2> /dev/null
+    welcome
+    select_action
+    select_root
+    select_collections
+    ask_detailed
+    select_packages
+    check_dependencies
+    confirm
+    if [ "$ACTION" = "UPGRADE" ] && [ -f /usr/bin/setup-helper ]; then
+	(
+            /usr/bin/setup-helper $ROOT &> $helperlogfile
+        ) | do_dialog --title " Please wait [3.4 -> 3.5 check]" --gauge "" 8 60 0
+    fi
+    install_packages
+    cat $helperlogfile 2> /dev/null
 }
 
 tmpfile=/tmp/tmp.$$
@@ -354,29 +328,13 @@ collfile=/tmp/collections.$$
 pkgfile=/tmp/packages.$$
 logfile=/tmp/log.$$
 helperlogfile=/tmp/log-helper.$$
+crux_dir=/crux
 neededfile=/tmp/needed.$$
 markedfile=/tmp/marked.$$
 
-bootloaders=(lilo grub2 grub2-efi syslinux)
-
-grep -q "prefix=*" /proc/cmdline
-if [ $? -eq 0 ]
-then
-	for opt in `cat /proc/cmdline`
-	do
-		echo $opt | grep -q "prefix="
-		if [ $? -eq 0 ]
-		then
-			p=`echo $opt | cut -d= -f2`
-			crux_dir=/media/${p}/crux
-		fi
-	done
-else
-	crux_dir=/media/crux
-fi
-
 # Detailed selection of packages
 DO_DETAILED="no"
+EXECUTE_SCRIPTS="yes"
 MISSINGDEPS=""
 
 trap "rm -f $tmpfile $pkgfile $collfile $neededfile $markedfile" 0 1 2 5 15
